version: '3'

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8080"
    volumes:
      - ./app