const optionTypes = {
  FETCH_OPTIONS_START: 'FETCH_OPTIONS_START',
  SET_OPTIONS: 'SET_OPTIONS',
  UPDATE_OPTION_START: 'UPDATE_OPTION_START',
  RESET_OPTIONS_START: 'RESET_OPTIONS_START',
  RESET_ALL_OPTIONS_START: 'RESET_ALL_OPTIONS_START',
};

export default optionTypes;
