const groupTypes = {
  ADD_NEW_GROUP_START: 'ADD_NEW_GROUP_START',
  FETCH_GROUP_START: 'FETCH_GROUP_START',
  SET_GROUP: 'SET_GROUP',
  FETCH_GROUPS_START: 'FETCH_GROUPS_START',
  SET_GROUPS: 'SET_GROUPS',
  UPDATE_GROUP_START: 'UPDATE_GROUP_START',
  DELETE_GROUP_START: 'DELETE_GROUP_START',
};

export default groupTypes;
