const userTypes = {
    LOGIN_USER_START: 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGOUT_USER_START: 'LOGOUT_USER_START',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    REGISTER_USER_START: 'REGISTER_USER_START',
    USER_ERROR: 'USER_ERROR'
};

export default userTypes;
