const memberTypes = {
    ADD_NEW_MEMBER_START: 'ADD_NEW_MEMBER_START',
    FETCH_MEMBER_START: 'FETCH_MEMBER_START',
    SET_MEMBER: 'SET_MEMBER',
    FETCH_MEMBERS_START: 'FETCH_MEMBERS_START',
    SET_MEMBERS: 'SET_MEMBERS',
    UPDATE_MEMBER_START: 'UPDATE_MEMBER_START',
    DELETE_MEMBER_START: 'DELETE_MEMBER_START'
};

export default memberTypes;
