const roleTypes = {
    ADD_NEW_ROLE_START: 'ADD_NEW_ROLE_START',
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    SET_ROLE: 'SET_ROLE',
    FETCH_ROLES_START: 'FETCH_ROLES_START',
    SET_ROLES: 'SET_ROLES',
    UPDATE_ROLE_START: 'UPDATE_ROLE_START',
    DELETE_ROLE_START: 'DELETE_ROLE_START'
};

export default roleTypes;
