const eventTypes = {
    ADD_NEW_EVENT_START: 'ADD_NEW_EVENT_START',
    FETCH_EVENT_START: 'FETCH_EVENT_START',
    SET_EVENT: 'SET_EVENT',
    FETCH_EVENTS_START: 'FETCH_EVENTS_START',
    SET_EVENTS: 'SET_EVENTS',
    UPDATE_EVENT_START: 'UPDATE_EVENT_START',
    DELETE_EVENT_START: 'DELETE_EVENT_START'
};

export default eventTypes;
